#!/bin/bash

# SPDX-FileCopyrightText: 2023 Christian Fletcher <mistrustfully@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

if [ -x $0.local ]; then
    $0.local "$@" || exit $?
fi
if [ -x tracked_hooks/$(basename $0) ]; then
    tracked_hooks/$(basename $0) "$@" || exit $?
fi
