#!/bin/bash

# SPDX-FileCopyrightText: 2023 Christian Fletcher <mistrustfully@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

function check {
	EXIT_CODE="$?"
	if [ $EXIT_CODE -ne 0 ]
	then
		echo $1
		exit $EXIT_CODE
	fi
}

# Are files correctly licensed?
reuse lint > /dev/null 2>&1
check "Code is not reuse compliant (check 'reuse lint'?)"

# Does our code compile?
npx roblox-ts build > /dev/null 2>&1
check "Code doesn't correctly compile (Check 'npx roblox-ts build'?)"

# Does our code have any linter warnings?
npx eslint src --max-warnings 0 > /dev/null 2>&1
check "Code has linter warnings (check 'npx eslint src'?)"

exit 0
